# Generated by Django 3.0.7 on 2020-07-01 11:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance_Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P01', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('strasse', models.CharField(max_length=80)),
                ('plz', models.CharField(max_length=20)),
                ('ort', models.CharField(max_length=80)),
                ('land', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 2', regex='^.{2}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anrede', models.CharField(max_length=80)),
                ('vorname', models.CharField(max_length=80)),
                ('zuname', models.CharField(max_length=80)),
                ('abteilung', models.CharField(max_length=80)),
                ('telefon', models.CharField(max_length=80)),
                ('fax', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('extranet_id', models.CharField(max_length=8)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kommentar', models.TextField()),
                ('meldetermin', models.PositiveSmallIntegerField()),
                ('bilanzstichtag', models.DateField()),
                ('absender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absender', to='models.Company')),
                ('absender_kontakt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absender_kontakt', to='models.Contact')),
                ('ersteller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ersteller', to='models.Company')),
                ('ersteller_kontakt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ersteller_kontakt', to='models.Contact')),
                ('melder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='melder', to='models.Company')),
                ('melder_kontakt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='melder_kontakt', to='models.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='K3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Company')),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.Report')),
            ],
        ),
    ]
