# Generated by Django 3.0.7 on 2020-07-01 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance_sheet',
            name='k3',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.K3'),
        ),
    ]
